output_dir: '../../data/a549/experiments'
module: src.experiments.model_pretraining
class: PretrainAeExperiment
run_params:
  data_config: {'data_fname':'../../data/a549_dex/processed/rna_data.csv',
                      'data_key':'seq_data', 'label_key':'label'}

  model_config : {'model_config':{'type':'GaussianMixtureVAE',
                        'hidden_dims':[1024, 512, 256, 128],
                        'n_components': 3,
                        'latent_dim': 50,
                        'input_dim':2613},
                        'optimizer_config':{'type':'rmsprop', 'lr':0.00001, 'weight_decay':0.0005},
                        'loss_config':{'type':'mae'}}

  latent_structure_model_config: {'model_config':{'type':'LatentClassifier', 'latent_dim':50, 'n_classes':3},
                      'optimizer_config':{'type':'adam', 'lr':0.00001},
                      'loss_config':{'type':'ce',}}

  domain_name: 'rna'
  num_epochs: 4000
  early_stopping: 100
  train_val_test_split: [0.6, 0.3, 0.1]
  batch_size: 32
  random_state: 1001


pipeline:
  - method: initialize_seq_data_set
  - method: initialize_data_loader_dict
  - method: initialize_domain_config
  - method: initialize_clf_model
  #- method: load_model
  #  params:
  #    weights_fname: '../../data/experiments/20200805_134219/best_vae.pth'
  - method: train_models
    params:
      gamma: 100.0
      lamb: 1.0
      save_freq: 100
      use_latent_structure_model: False

